global:
   
   scrape_interval:     15s
   evaluation_interval: 15s
   external_labels:
           monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'graphana'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.146:3000']
